### ISSUE TITLE
Getting an error.

### ISSUE THREAD

**Issue by Jeet1994** [danmack/sierpinski-rs#1]
I am a beginner in Rust. 

I have tried running your code in my system, I get the following error,

```
H:\sierpinski-rs-master\src>rustc main.rs
error[E0463]: can't find crate for `image`
 --> main.rs:5:1
  |
5 | extern crate image;
  | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error


H:\sierpinski-rs-master\src>

```

Any help is appreciated.

**Comment by danmack** [comment]
I see you are on windows - which version of rust are you using?   I will try to reproduce the error.   I noticed that you are running the rust compiler manually - can you try this instead:

  H:\sierpinski-rs-master> cargo run

Do you get the same error ?

**Comment by danmack** [comment]
So yeah, I reproduced the error you got as well and it is indeed due to you trying to compile the .rs file with just the rustc executable.   It turns out that it *could* work, but you would need to pass in a bunch of additional arguments to rustc to make it work.

The conventional way of building rust code is via the "cargo" command.  For example, if you just wanted to build the main.rs file, you could run "cargo build" from the top level directory of the rust project like so (I'll pass in verbose to show you what get's passed to rustc):

 % cargo build --verbose
<snip>
   Compiling triangle v0.1.0 (file:///Users/mack/src/sierpinski-rs)
     Running `rustc src/main.rs --crate-name triangle --crate-type bin -g -C metadata=0202e9992662af0f --out-dir /Users/mack/src/sierpinski-rs/target/debug --emit=dep-info,link -L dependency=/Users/mack/src/sierpinski-rs/target/debug/deps --extern rand=/Users/mack/src/sierpinski-rs/target/debug/deps/librand-49a08859d086fffe.rlib --extern image=/Users/mack/src/sierpinski-rs/target/debug/deps/libimage-1ef1c5676f65109e.rlib -L native=/Users/mack/src/sierpinski-rs/target/debug/build/miniz-sys-60c8d67696f63a43/out`
    Finished debug [unoptimized + debuginfo] target(s) in 19.15 secs


any way - hope this helps.   Dan

**Comment by Jeet1994** [comment]
Worked great :D Thanks
